# Configurations for the recommendations sytem - python backend

# Recommendation server hostname and port
host: localhost
port: 8082

# Username and password credentials for the authorization for the server
username: admin
password: admin

# Whether to secure the server endpoint with SSL
https_enabled: False

search_details_valid_months: 3            # Search queries before the valid period will be removed
minimum_search_queries: 5                 # Search queries are deleted after the validity period only if this minimum no. is available.
minimum_APIs_to_start_recommendations: 20 # Minimum number of APIs needs to be published in devportal to start giving recommendations
cron_job_interval_in_hours: 24            # Cron job interval in hours to update user_recommendation collection

# URL to connect to the Mongodb
mongodb_url: localhost:27017/

log_level: INFO